spring:
  datasource:
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 32
      max-lifetime: 1800000
      # 超时，毫秒（单位）
      connection-timeout: 300000
      connection-test-query: SELECT 1
      register-mbeans: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.139.128/dj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
    username: admin
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  redis:
    host: 192.168.139.128
    lettuce:
      pool:
        max-active: 512
        max-wait: 10s
        min-idle: 16
    password: '123456'
    port: 6379
    timeout: 10s
server:
  port: 8080